/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * gui.java
 *
 * Created on Sep 2, 2010, 7:03:50 PM
 */
package graph;

import java.awt.Font;
import java.awt.Point;
import javax.swing.JOptionPane;
import java.util.ArrayList;
import javax.swing.JLabel;
import javax.swing.JTextField;

/**
 *
 * @author alex
 */
public class gui extends javax.swing.JFrame {

    static ArrayList<Point> points = new ArrayList<Point>();

    /** Creates new form gui */
    public gui() {
        initComponents();


    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        jPanel3 = new javax.swing.JPanel();
        XY = new javax.swing.JLabel();
        YZ = new javax.swing.JLabel();
        XZ = new javax.swing.JLabel();
        anglex = new javax.swing.JLabel();
        angley = new javax.swing.JLabel();
        anglez = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jComboBox2 = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        jLabel10 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jComboBox3 = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jTextField4 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Plotter");
        setBounds(new java.awt.Rectangle(700, 0, 0, 0));
        setResizable(false);

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jButton1.setText("Draw");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Point X");

        jLabel2.setText("Point Y");

        jLabel3.setText("Point Z");

        jLabel4.setText("Format is x, y");

        jButton3.setText("Sample Graph");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jCheckBox4.setText("Do not draw grid (may reduce lag)");
        jCheckBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox4ActionPerformed(evt);
            }
        });

        jCheckBox5.setText("Auto resize scale factor to fit triangle best.");
        jCheckBox5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jTextField2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                                    .addComponent(jTextField3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                                    .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE))
                                .addGap(10, 10, 10))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jCheckBox5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                                            .addComponent(jLabel1))
                                        .addGap(86, 86, 86)
                                        .addComponent(jLabel4))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jButton3)
                                        .addComponent(jButton1)))
                                .addGap(96, 96, 96))))
                    .addComponent(jCheckBox4)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox5)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox4)
                    .addComponent(jButton3))
                .addGap(25, 25, 25))
        );

        jTabbedPane1.addTab("Set Points", jPanel1);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        XY.setText("XY:");

        YZ.setText("YZ:");

        XZ.setText("XZ:");

        anglex.setText("< X:");

        angley.setText("< Y:");

        anglez.setText("< Z:");

        jCheckBox1.setText("Round results");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        jCheckBox2.setText("Label Lengths");
        jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2ActionPerformed(evt);
            }
        });

        jCheckBox3.setText("Label < Measures");
        jCheckBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox3ActionPerformed(evt);
            }
        });

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("<html>Unrounded Graph results are truncated.</html>");
        jLabel6.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(XY, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                                .addComponent(YZ, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(XZ, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 150, Short.MAX_VALUE))
                        .addComponent(anglex, javax.swing.GroupLayout.DEFAULT_SIZE, 313, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(angley, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(anglez, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jCheckBox2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jCheckBox1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jCheckBox3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(XY)
                    .addComponent(jCheckBox1))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(YZ)
                    .addComponent(jCheckBox2))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(XZ)
                    .addComponent(jCheckBox3))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(anglex, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(angley)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(anglez))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(80, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Data Result", jPanel3);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel5.setText("Scale Factor (Small factors may cause lag)");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "3", "1", "2", "4", "5", "6", "7", "8", "9", "10" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        jLabel7.setText("Truncation level for graphing (Default 3)");

        jSpinner1.setModel(new javax.swing.SpinnerNumberModel(50, 0, 255, 5));
        jSpinner1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinner1StateChanged(evt);
            }
        });

        jLabel10.setText("Alpha level of grid, higher means more opaque (255 max, 0 min)");

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2", "1" }));

        jLabel11.setText("Drag Factor (1 drags faster)");

        jLabel12.setText("Note - Right click graph to zoom in or out by one level");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSpinner1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7)
                    .addComponent(jLabel11)
                    .addComponent(jLabel10))
                .addContainerGap(140, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(101, 101, 101)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))))
                .addContainerGap(56, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Settings", jPanel2);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "XY", "YZ", "XZ", "<X", "<Y", "<Z" }));
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });

        jLabel8.setText("Select variable to show solution for:");

        jButton2.setText("<html>Refresh Solution (Used when a setting is changed, e.g font size) </html>");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });

        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });

        jLabel9.setText("Font Size");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 355, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addGap(18, 18, 18)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel8)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel9)
                            .addGap(74, 74, 74)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE))))
                .addGap(10, 10, 10))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );

        jTabbedPane1.addTab("Solution", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        lazy();
        if (autoResize()) {
            jCheckBox5ActionPerformed(null);
        }
        calcData();
        Main.m.repaint();
    }//GEN-LAST:event_jButton1ActionPerformed
    void lazy() {
        points.clear();
        try {

            for (int i = 1; i < 4; i++) {
                //reflection ?
                JTextField field = (JTextField) gui.class.getDeclaredField("jTextField" + i).get(this);
                if (!field.getText().contains(",")) {
                    throw new NumberFormatException("no comma");
                }
                String[] point = field.getText().trim().split(",");

                points.add(Main.pointConvert(new Point(Integer.parseInt(point[0].trim()), Integer.parseInt(point[1].trim()))));
            }
            points.add(points.get(0)); //Duplicate first point as 4th for looping purposes
            points.add(points.get(1)); //Duplicate 2nd as 5th for looping as well

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Error parsing point.");
            return;
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Reflection error! Stack trace printed.");
            e.printStackTrace();
            return;
        }
    }

    public int getDrag() {
        int i = jComboBox4.getSelectedIndex();
        return i;
    }

    void calcData() {
        boolean round = jCheckBox1.isSelected();
        String[] foo = {"XY", "YZ", "XZ"};
        String[] p = {"X", "Y", "Z"};
        for (int i = 0; i < 3; i++)//additional fourth/fifth point
        {
            //Complicated reflection .
            try {
                ((JLabel) gui.class.getDeclaredField(foo[i]).get(this)).setText(foo[i] + ": " + Util.distance(Main.original(points.get(i)), Main.original(points.get(i + 1)), round));
                ((JLabel) gui.class.getDeclaredField("angle" + p[i].toLowerCase()).get(this)).setText("< " + p[i] + ": " + Util.angle(Main.original(points.get(i)), Main.original(points.get(i + 1)), Main.original(points.get(i + 2)), round) + "°");
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
        /*XY.setText("XY: " + Util.distance(Main.original(points.get(0)), Main.original(points.get(1)), round));
        XZ.setText("XZ: " + Util.distance(Main.original(points.get(0)), Main.original(points.get(2)), round));
        YZ.setText("YZ: " + Util.distance(Main.original(points.get(1)), Main.original(points.get(2)), round));
        anglex.setText("< X: " + Util.angle(Main.original(points.get(0)), Main.original(points.get(1)), Main.original(points.get(2)), round) + "°");
        angley.setText("< Y: " + Util.angle(Main.original(points.get(1)), Main.original(points.get(2)), Main.original(points.get(0)), round) + "°");
        anglez.setText("< Z: " + Util.angle(Main.original(points.get(2)), Main.original(points.get(0)), Main.original(points.get(1)), round) + "°");
         * */

    }
    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        try {
            int scale = Integer.parseInt((String) jComboBox1.getSelectedItem());
            if (scale == Main.getScale()) { // same scale
                return;
            }
            Main.setScale(scale);
            if (points.size() > 0) {
                lazy();
            }
            Main.setGridRepaint(true);
            Main.m.repaint();
        } catch (Exception e) {
        } //the only time it throws an exception is when i set the initial selection o-o
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        if (points.size() > 0) {
            calcData();
            if (labelLength() || labelAngle()) {
                Main.m.repaint();
            }
        }
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed
        Main.m.setDrawMeasure(labelLength());
        Main.m.repaint();
    }//GEN-LAST:event_jCheckBox2ActionPerformed

    private void jCheckBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox3ActionPerformed
        Main.m.setLabelAngles(labelAngle());
        Main.m.repaint();
    }//GEN-LAST:event_jCheckBox3ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        int level = Integer.parseInt((String) jComboBox2.getSelectedItem());
        Util.setTruncation(level);
        if (points.size() > 0) {
            Main.m.repaint();
        }
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        if (!jTextField4.getText().equals("")) {
            try {
                jTextArea1.setFont(new Font("Monospaced", Font.PLAIN, Integer.parseInt(jTextField4.getText())));
            } catch (Exception e) {
                //Probs number format exception
            }
        }
        if (points.size() > 0) {
            jTextArea1.setText("");
            String text = (String) jComboBox3.getSelectedItem();
            Point a = Main.original(points.get(0));
            Point b = Main.original(points.get(1));
            Point c = Main.original(points.get(2));
            Point x = null;
            Point y = null;
            String p1name = "";
            String p2name = "";
            if (text.equalsIgnoreCase("XY") || text.equalsIgnoreCase("XZ") || text.equalsIgnoreCase("YZ")) {
                if (text.equals("XY")) {
                    p1name = "X";
                    p2name = "Y";
                    x = a;
                    y = b;
                } else if (text.equals("XZ")) {
                    p1name = "X";
                    p2name = "Z";
                    x = a;
                    y = c;
                } else if (text.equals("YZ")) {
                    p1name = "Y";
                    p2name = "Z";
                    x = b;
                    y = c;
                }
                jTextArea1.append("Solution :\n");
                jTextArea1.append("Set up the distance formula.\n");
                jTextArea1.append("√((x₁-x₂)²+(y₁-y₂)²)\n");
                jTextArea1.append("Substitute variables :\n");
                jTextArea1.append(p1name + "(" + x.x + ", " + x.y + ") and " + p2name + "(" + y.x + ", " + y.y + ") are our points to plug in.\n");
                jTextArea1.append("Let us assume x₁ is " + x.x + ", x₂ is " + y.x + ", y₁ is " + x.y + ", and y₂ is " + y.y + ".\n");
                jTextArea1.append("Plug in the variables into the formula.\n");
                jTextArea1.append("√((" + x.x + "-" + y.x + ")²+(" + x.y + "-" + y.y + ")²)\n");
                jTextArea1.append("Simplify.\n");
                jTextArea1.append("√((" + (x.x - y.x) + ")²+(" + (x.y - y.y) + ")²)\n");
                float squared = (float) Math.pow(x.x - y.x, 2);
                float squared2 = (float) Math.pow(x.y - y.y, 2);
                jTextArea1.append("√(" + squared + "+" + squared2 + "))\n");
                jTextArea1.append("√(" + (squared + squared2) + ")\n");
                jTextArea1.append("Result:\n");
                jTextArea1.append(text + "=" + Util.distance(x, y, round()) + (round() ? " (Result is rounded)" : ""));
            } else if (text.equals("<X") || text.equals("<Y") || text.equals("<Z")) {
                double prime = 0;
                double beta = 0;
                double gamma = 0;
                String name1 = "";
                String name2 = "";
                String name3 = "";
                if (text.equals("<X")) {
                    prime = Util.yz();
                    name1 = "YZ";
                    beta = Util.xy();
                    name2 = "XY";
                    gamma = Util.xz();
                    name3 = "XZ";
                } else if (text.equals("<Y")) {
                    prime = Util.xz();
                    name1 = "XZ";
                    beta = Util.yz();
                    name2 = "YZ";
                    gamma = Util.xy();
                    name3 = "XY";
                } else if (text.equals("<Z")) {
                    prime = Util.xy();
                    name1 = "XY";
                    beta = Util.xz();
                    name2 = "XZ";
                    gamma = Util.yz();
                    name3 = "YZ";
                }
                double t1 = Util.truncate(prime);
                double t2 = Util.truncate(beta);
                double t3 = Util.truncate(gamma);
                jTextArea1.append("Solution : (Numbers may appear truncated during solution but final solution uses untruncated numbers to produce result)\n");
                jTextArea1.append("Set up the law of cosines.\n");
                jTextArea1.append("a²=b²+c²-2bc×Cos(A)\n");
                jTextArea1.append("Set variables. \n");
                jTextArea1.append("a=" + t1 + "(" + name1 + "), b=" + t2 + "(" + name2 + "), and c=" + t3 + "(" + name3 + ").\n");
                jTextArea1.append("Substitute in variables.\n");
                jTextArea1.append("(" + t1 + ")²=(" + t2 + ")²+(" + t3 + ")²-2×" + t2 + "×" + t3 + "×Cos(A)\n");
                jTextArea1.append("Simplify.\n");
                double powed1 = Util.truncate(Util.square(t1));
                double powed2 = Util.truncate(Util.square(t2));
                double powed3 = Util.truncate(Util.square(t3));
                jTextArea1.append(powed1 + "=" + powed2 + "+" + powed3 + "+(" + (-2 * t2 * t3) + "×Cos(A))\n");
                jTextArea1.append(powed1 + "=" + (powed2 + powed3) + "+(" + (-2 * t2 * t3) + "×Cos(A))\n");
                jTextArea1.append(Util.truncate(powed1 - (powed2 + powed3)) + "=" + (-2 * t2 * t3) + "×Cos(A)\n");
                jTextArea1.append("(" + Util.truncate(powed1 - (powed2 + powed3)) + ")/(" + (-2 * t2 * t3) + ")=Cos(A)\n");
                jTextArea1.append("m" + text + "=arccos(" + ((Util.truncate(powed1 - (powed2 + powed3)) / (-2 * t2 * t3))) + ")\n");
                jTextArea1.append("Result:\n");
                jTextArea1.append("m" + text + "=" + Util.angle(prime, beta, gamma, round()) + "°" + (round() ? " (Result is rounded)" : ""));
            }
        } else {
            JOptionPane.showMessageDialog(this, "Please plot a graph first.");
        }
    }//GEN-LAST:event_jComboBox3ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        jTextField1.setText("0,0");
        jTextField2.setText("5,0");
        jTextField3.setText("0,5");
        jButton1ActionPerformed(null);
        JOptionPane.showMessageDialog(this, "Learn from this.");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jCheckBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox4ActionPerformed
        Main.setGridRepaint(true);
        Main.m.repaint();
    }//GEN-LAST:event_jCheckBox4ActionPerformed

    private void jCheckBox5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox5ActionPerformed
        if (points.size() > 0) {
            int orig = Main.getScale();
            main:
            for (int i = Main.possible.size() - 1; i >= 0; i--) {
                int scalee = Main.possible.get(i);
                //   System.out.println("Scale " + scalee);
                for (int j = 0; j < 3; j++) {
                    //System.out.println(j);
                    if (!Main.m.pointOnScreen(points.get(j), scalee)) {
                        //     System.out.println("failed");
                        if (i != 0) { //last
                            continue main;

                        }
                    }
                }

                Main.setScale(scalee);
                // System.out.println(Main.getScale());
                Main.setGridRepaint(true);
                Main.refreshPointsToScale(orig);
                jComboBox1.setSelectedIndex(i);
                break;
            }
            if (evt != null) {
                Main.m.repaint();

            }
        }
    }//GEN-LAST:event_jCheckBox5ActionPerformed

    private void jSpinner1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinner1StateChanged
        if (jSpinner1.getModel().getValue() instanceof Integer) {
            int i = (Integer) jSpinner1.getModel().getValue();
            if (Main.getAlpha() != i) {
                Main.setAlpha(i);
                Main.setGridRepaint(true);
                Main.m.repaint();
            }
        }

    }//GEN-LAST:event_jSpinner1StateChanged
    boolean round() {
        return jCheckBox1.isSelected();
    }

    boolean labelLength() {
        return jCheckBox2.isSelected();
    }

    boolean labelAngle() {
        return jCheckBox3.isSelected();
    }

    boolean dontdrawGrid() {
        return jCheckBox4.isSelected();
    }

    boolean autoResize() {
        return jCheckBox5.isSelected();
    }
    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel XY;
    private javax.swing.JLabel XZ;
    private javax.swing.JLabel YZ;
    private javax.swing.JLabel anglex;
    private javax.swing.JLabel angley;
    private javax.swing.JLabel anglez;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    static javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JComboBox jComboBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
